# Generated by Django 4.0.2 on 2022-02-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='article_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
